import Head from "next/head";
import { useRouter } from "next/router";
import { ProductCard } from "../components/ProductCard";
import { CanceledModal, SuccessModal } from "../components/StatusModals";
import products from "../content/products.json";

export default function Home() {
  const router = useRouter();
  const { status } = router.query;
  return (
    <>
      <Head>
        <title>Skenifor</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className=" mt-16  py-11 flex flex-col items-center">
        {status === "cancel" && <CanceledModal />}
        {status == "success" && <SuccessModal />}
        <div className="flex flex-col items-center gap-24">
          <h1 className="font-extrabold text-6xl">Tere tulemast Skenifori e-poodi</h1>
          <div className="grid auto-cols-max grid-cols-1  md:grid-cols-2 lg:grid-cols-4  gap-6">
            {products.map((item) => (
              <ProductCard key={item.id} {...item} />
            ))}
          </div>
        </div>
      </section>
    </>
  );
}
